[Unit]
Wants=oneplus6t-pacman-keyring.service oneplus6t-hyperrotation-build.service oneplus6t-wvkbd-build.service oneplus6t-touch-osk.service
After=oneplus6t-pacman-keyring.service
After=oneplus6t-hyperrotation-build.service oneplus6t-wvkbd-build.service oneplus6t-touch-osk.service

[Service]
ExecStart=
ExecStart=-/usr/bin/agetty --autologin alarm --noclear %I $TERM
