#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROFILE="${1:-oneplus-fajita}"
PROFILE_DIR="$ROOT_DIR/profiles/$PROFILE"
OVERLAY="$PROFILE_DIR/overlay"
HYPR_CONF="$OVERLAY/home/alarm/.config/hypr/conf.d/10-oneplus6t-controls.conf"
WVKBD_VENDOR="$ROOT_DIR/vendor/wvkbd"
PROFILE_FILE="$OVERLAY/home/alarm/.profile"
FOOT_CONF="$OVERLAY/home/alarm/.config/foot/foot.ini"
AUDIO_PROFILE="$OVERLAY/usr/local/bin/oneplus6t-audio-profile"
AUDIO_ROUTE="$OVERLAY/usr/local/bin/oneplus6t-audio-route"
AUDIO_TEST="$OVERLAY/usr/local/bin/oneplus6t-audio-test"
FAJITA_UCM="$OVERLAY/usr/share/alsa/ucm2/OnePlus/fajita"
SDM845_UCM="$OVERLAY/usr/share/alsa/ucm2/conf.d/sdm845"
O6T_UCM="$OVERLAY/usr/share/alsa/ucm2/O6T"
SND_SOC_SDM845_UCM="$OVERLAY/usr/share/alsa/ucm2/conf.d/snd_soc_sdm845"
ROOTFS_BUILDER="$ROOT_DIR/scripts/build-rootfs-image.sh"
CONFIG_ENV="$PROFILE_DIR/config.env"
INSTALL_RELEASE="$ROOT_DIR/scripts/install-release.sh"
FULL_INSTALLER="$ROOT_DIR/scripts/run-full-installer-from-start.sh"
FETCH_RELEASE_INPUTS="$ROOT_DIR/scripts/fetch-release-inputs.sh"
MAKE_RELEASE_INPUTS="$ROOT_DIR/scripts/make-release-inputs-bundle.sh"
PACKAGE_PREBUILT="$ROOT_DIR/scripts/package-prebuilt-flash-bundle.sh"
PUBLIC_LAUNCHER="$ROOT_DIR/oneplus6t-install"
PACKAGE_REVIEW="$ROOT_DIR/scripts/review-profile-packages.sh"
PACKAGE_ALIASES="$ROOT_DIR/scripts/package-name-aliases.sh"
BOOTANIMATION_SCRIPT="$ROOT_DIR/scripts/make-bootanimation.sh"
BOOTANIMATION_REPLACE_SCRIPT="$ROOT_DIR/scripts/replace-boot-video.sh"
BOOTANIMATION_ZIP="$OVERLAY/usr/share/oneplus6t/bootanimation.zip"
README="$ROOT_DIR/README.md"
LICENSE_FILE="$ROOT_DIR/LICENSE"
NOTICE_FILE="$ROOT_DIR/NOTICE"
THIRD_PARTY_NOTICES="$ROOT_DIR/docs/THIRD-PARTY-NOTICES.md"
FUNDING_FILE="$ROOT_DIR/.github/FUNDING.yml"

fail() {
  printf 'profile-ui-check: %s\n' "$*" >&2
  exit 1
}

fail_missing_submodule() {
  local path="$1"
  cat >&2 <<EOF
profile-ui-check: missing source submodule: ${path#"$ROOT_DIR/"}

Run:
  git submodule update --init --recursive

Then rerun the installer.
EOF
  exit 1
}

need_file() {
  local path="$1"
  [[ -f "$path" ]] || fail "missing file: ${path#"$ROOT_DIR/"}"
}

need_text() {
  local path="$1"
  local text="$2"
  grep -Fq -- "$text" "$path" || fail "missing text in ${path#"$ROOT_DIR/"}: $text"
}

reject_text() {
  local path="$1"
  local text="$2"
  if grep -Fq -- "$text" "$path"; then
    fail "unexpected text in ${path#"$ROOT_DIR/"}: $text"
  fi
}

need_executable() {
  local path="$1"
  [[ -x "$path" ]] || fail "missing executable: ${path#"$ROOT_DIR/"}"
}

need_file "$PROFILE_FILE"
need_text "$PROFILE_FILE" "exec dbus-run-session start-hyprland"
need_text "$PROFILE_FILE" "exec dbus-run-session /usr/local/bin/start-hyprland"
need_text "$PROFILE_FILE" "exec /usr/local/bin/start-hyprland"

need_executable "$OVERLAY/usr/local/bin/start-hyprland"
need_executable "$OVERLAY/usr/local/bin/oneplus6t-lock"
need_executable "$OVERLAY/usr/local/bin/oneplus6t-osk"
need_executable "$OVERLAY/usr/local/bin/oneplus6t-terminal"
[[ ! -e "$OVERLAY/usr/local/bin/tlauncher" ]] || fail "remove profile-specific tlauncher from public installer overlay"
need_executable "$OVERLAY/usr/local/bin/oneplus6t-volume"
need_executable "$OVERLAY/usr/local/bin/oneplus6t-screenshot"
need_executable "$OVERLAY/usr/local/bin/oneplus6t-auto-rotate"
[[ ! -e "$OVERLAY/usr/local/bin/oneplus6t-boot-banner" ]] || fail "remove tty ASCII boot banner from crashdump-safe profile"
need_text "$OVERLAY/usr/local/bin/oneplus6t-auto-rotate" "retrying without leaving the Hyprland session"
need_text "$OVERLAY/usr/local/bin/oneplus6t-auto-rotate" "monitor-sensor exited; retrying"
need_text "$PROFILE_DIR/config.env" "earlycon loglevel=7"
need_text "$PROFILE_DIR/config.env" "PMOS_NOSPLASH"
need_text "$PROFILE_DIR/config.env" "PMOS_NO_OUTPUT_REDIRECT"
reject_text "$PROFILE_DIR/config.env" "quiet loglevel=3"
need_executable "$BOOTANIMATION_SCRIPT"
need_executable "$BOOTANIMATION_REPLACE_SCRIPT"
need_executable "$OVERLAY/usr/local/bin/oneplus6t-bootanimation"
need_file "$BOOTANIMATION_ZIP"
need_text "$BOOTANIMATION_SCRIPT" "-map 0:v:0 -an"
need_text "$BOOTANIMATION_SCRIPT" "BOOTANIMATION_FORMAT"
need_text "$BOOTANIMATION_REPLACE_SCRIPT" "BOOTANIMATION_MAX_SECONDS=45"
need_text "$BOOTANIMATION_REPLACE_SCRIPT" "BOOTANIMATION_FORCE"
need_text "$BOOTANIMATION_REPLACE_SCRIPT" "Audio is ignored"
need_text "$BOOTANIMATION_REPLACE_SCRIPT" "scripts/make-bootanimation.sh"
need_text "$OVERLAY/usr/local/bin/oneplus6t-bootanimation" "ONEPLUS6T_BOOTANIMATION_MAX_SECONDS"
need_text "$OVERLAY/usr/local/bin/oneplus6t-bootanimation" "/dev/fb0"
need_text "$OVERLAY/usr/local/bin/oneplus6t-bootanimation" "parts = parse_desc"
need_text "$OVERLAY/usr/local/bin/oneplus6t-bootanimation" "while time.monotonic() < deadline"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-bootanimation.service" "Before=getty@tty1.service"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-bootanimation.service" "ONEPLUS6T_BOOTANIMATION_MAX_SECONDS=45"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-bootanimation.service" "StandardOutput=null"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-bootanimation.service" "StandardError=journal"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-bootanimation.service" "Nice=10"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-bootanimation.service" "IOSchedulingClass=idle"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-bootanimation.service" "CPUSchedulingPolicy=batch"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-bootanimation.service" "TimeoutStartSec=55"
if command -v unzip >/dev/null 2>&1; then
  unzip -p "$BOOTANIMATION_ZIP" desc.txt 2>/dev/null | grep -Eq '^[0-9]+ [0-9]+ [0-9]+$' || \
    fail "bootanimation.zip missing Android-style desc.txt header"
  if unzip -l "$BOOTANIMATION_ZIP" | grep -Eiq '\.(mp3|wav|ogg|aac|m4a|mp4|mov)$|audio'; then
    fail "bootanimation.zip must not contain audio or video streams"
  fi
fi
need_executable "$AUDIO_PROFILE"
need_executable "$AUDIO_ROUTE"
need_executable "$AUDIO_TEST"
need_executable "$OVERLAY/usr/local/bin/oneplus6t-call-audio-watch"
need_executable "$OVERLAY/usr/local/bin/oneplus6t-camera-info"
need_executable "$OVERLAY/usr/local/sbin/oneplus6t-cpu-power"
need_executable "$OVERLAY/usr/local/sbin/oneplus6t-gps"
need_executable "$OVERLAY/usr/local/sbin/oneplus6t-haptics-test"
need_executable "$OVERLAY/usr/local/sbin/oneplus6t-keychords"
need_executable "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk"
need_executable "$OVERLAY/usr/local/sbin/oneplus6t-install-wvkbd"
need_executable "$OVERLAY/usr/local/sbin/oneplus6t-init-pacman-keyring"
[[ -f "$WVKBD_VENDOR/Makefile" ]] || fail_missing_submodule "$WVKBD_VENDOR"
need_file "$WVKBD_VENDOR/Makefile"
need_file "$WVKBD_VENDOR/layout.deskintl.h"
need_file "$WVKBD_VENDOR/keymap.deskintl.h"
need_file "$WVKBD_VENDOR/keyboard.c"
need_file "$WVKBD_VENDOR/main.c"
need_text "$WVKBD_VENDOR/layout.deskintl.h" "KEY_F1"
need_text "$WVKBD_VENDOR/layout.deskintl.h" "KEY_F12"
need_text "$WVKBD_VENDOR/layout.deskintl.h" "\"Sup\""
need_text "$WVKBD_VENDOR/layout.deskintl.h" "Super"
need_text "$WVKBD_VENDOR/keymap.deskintl.h" "Super_L"
need_text "$WVKBD_VENDOR/main.c" "zwlr_layer_surface_v1_set_size(layer_surface, 0, height)"
need_text "$WVKBD_VENDOR/README.md" "SIGUSR1 = hide"
need_text "$OVERLAY/usr/local/bin/oneplus6t-osk" "wvkbd-deskintl"
need_text "$OVERLAY/usr/local/bin/oneplus6t-osk" "full screen width"
need_text "$OVERLAY/usr/local/bin/oneplus6t-osk" "ONEPLUS6T_OSK_HEIGHT:-864"
need_text "$OVERLAY/usr/local/bin/oneplus6t-osk" "ONEPLUS6T_OSK_LANDSCAPE_HEIGHT:-520"
need_text "$OVERLAY/usr/local/bin/oneplus6t-osk" "kill -USR1"
need_text "$OVERLAY/usr/local/bin/oneplus6t-osk" "kill -USR2"

need_file "$HYPR_CONF"
need_file "$CONFIG_ENV"
need_file "$FOOT_CONF"
need_file "$INSTALL_RELEASE"
need_file "$FULL_INSTALLER"
need_executable "$PACKAGE_REVIEW"
need_file "$PACKAGE_ALIASES"
need_executable "$PUBLIC_LAUNCHER"
need_executable "$FETCH_RELEASE_INPUTS"
need_executable "$MAKE_RELEASE_INPUTS"
need_executable "$PACKAGE_PREBUILT"
[[ ! -e "$ROOT_DIR/workingdoc-run-full-installer-from-start" ]] || fail "remove stale root workingdoc-run-full-installer-from-start wrapper"
need_file "$LICENSE_FILE"
need_file "$NOTICE_FILE"
need_file "$THIRD_PARTY_NOTICES"
need_file "$FUNDING_FILE"
need_text "$LICENSE_FILE" "OnePlus 6T Arch Linux Installer Original Ownership, Terms and Yield-Back"
need_text "$LICENSE_FILE" "O6T-LINUX-1.0"
need_text "$LICENSE_FILE" "BOOTY-1.1 Booty Original Ownership Terms"
need_text "$LICENSE_FILE" "All rights not expressly granted are reserved"
need_text "$LICENSE_FILE" "Project Notice Files"
need_text "$LICENSE_FILE" "No recipient may relicense the Software"
need_text "$LICENSE_FILE" "Failure to provide the share-back materials on time is a licence breach"
need_text "$LICENSE_FILE" "Third-party components and materials remain governed by their"
need_text "$LICENSE_FILE" "It is not approved by the Open Source Initiative"
need_text "$NOTICE_FILE" "OnePlus 6T Arch Linux ARM Installer"
need_text "$NOTICE_FILE" "Copyright (c) 2026 Toni McQueen"
need_text "$NOTICE_FILE" "BOOTY-1.1 Booty Original Ownership Terms"
need_text "$NOTICE_FILE" "docs/THIRD-PARTY-NOTICES.md"
need_text "$THIRD_PARTY_NOTICES" "Third-Party Notices"
need_text "$FUNDING_FILE" "github: [mcqueentrading]"
need_text "$FUNDING_FILE" "https://tonimcqueen.com/pay/"
need_text "$FUNDING_FILE" "https://gofund.me/283160597"
need_text "$README" "## Licence And Notices"
need_text "$README" "source-available under a custom licence"
need_text "$README" "O6T-LINUX-1.0"
need_text "$README" "BOOTY-1.1 Booty Original Ownership Terms"
need_text "$README" "Open Source Initiative approved open-source"
need_text "$README" "docs/THIRD-PARTY-NOTICES.md"
need_text "$README" "## Our Ethics And Morals"
need_text "$README" "This repository is meant to be reproducible and honest"
reject_text "$README" "## Sponsored Preview Boundaries"
need_text "$PUBLIC_LAUNCHER" "./scripts/check-phone.sh"
need_text "$PUBLIC_LAUNCHER" "fastboot devices -l"
need_text "$PUBLIC_LAUNCHER" "./scripts/run-full-installer-from-start.sh"
need_text "$PUBLIC_LAUNCHER" "Troubleshooting:"
need_text "$PUBLIC_LAUNCHER" "FLASH"
need_text "$PUBLIC_LAUNCHER" "confirm_after_banner"
need_text "$PUBLIC_LAUNCHER" "First: this launcher checks USB/fastboot, then the installer builds the image."
need_text "$PUBLIC_LAUNCHER" "You will be prompted with warnings before any destructive fastboot flash."
need_text "$PUBLIC_LAUNCHER" "Are you ready to continue? [y/N]"
need_text "$PUBLIC_LAUNCHER" "Stopped before phone checks, build, or flash."
need_text "$README" "Please pay me at least a \$1+ please"
need_text "$README" "TARGET ACQUIRED: FAIRPHONE 5"
need_text "$README" "1920x1080p external desktop"
need_text "$README" "portable PC in your pocket"
need_text "$README" "5th generation mobile networks"
need_text "$README" "AI acceleration path"
need_text "$README" "Repairability is designed in"
need_text "$README" "https://gofund.me/283160597"
need_text "$README" "contact@tonimcqueen.com"
need_text "$PUBLIC_LAUNCHER" "please pay me at least a \$1+ please"
need_text "$PUBLIC_LAUNCHER" "TARGET ACQUIRED: FAIRPHONE 5"
need_text "$PUBLIC_LAUNCHER" "https://tonimcqueen.com/pay/"
need_text "$PUBLIC_LAUNCHER" "https://gofund.me/283160597"
need_text "$PUBLIC_LAUNCHER" "contact@tonimcqueen.com"
need_text "$PUBLIC_LAUNCHER" "Fairphone 5"
need_text "$INSTALL_RELEASE" "INSTALL_APP_LAUNCHER_PACKAGE"
need_text "$INSTALL_RELEASE" "INSTALL_APP_LAUNCHER_KEY"
need_text "$INSTALL_RELEASE" "INSTALL_KERNEL_TRACK"
need_text "$INSTALL_RELEASE" "prompt_for_kernel_track"
need_text "$INSTALL_RELEASE" "Kernel track [stable kernel or camera kernel; Enter=stable]"
need_text "$INSTALL_RELEASE" "Camera kernel warning:"
need_text "$INSTALL_RELEASE" "experimental IMX519/camera kernel track"
need_text "$INSTALL_RELEASE" "kernel: stable PMOS 6.9 SDM845 snapshot"
need_text "$INSTALL_RELEASE" "kernel: experimental IMX519 camera kernel"
need_text "$INSTALL_RELEASE" "Set up a SUPER-key app launcher shortcut?"
need_text "$INSTALL_RELEASE" "Application launcher package, for example nwg-menu, fuzzel, wofi, or rofi"
need_text "$INSTALL_RELEASE" "default_launcher_command_for_package"
need_text "$INSTALL_RELEASE" "wofi --show drun"
need_text "$INSTALL_RELEASE" "rofi -show drun"
need_text "$INSTALL_RELEASE" "Reserved: SUPER+Q terminal, SUPER+H keyboard kill, SUPER+C close, SUPER+K keyboard toggle, SUPER+1..0 workspaces."
need_text "$INSTALL_RELEASE" "prompt_for_optional_value"
need_text "$INSTALL_RELEASE" "append_package_to_manifest"
need_text "$README" "wofi --show drun"
need_text "$README" "rofi -show drun"
need_text "$ROOT_DIR/scripts/build-release.sh" "INSTALL_APP_LAUNCHER_PACKAGE"
need_text "$ROOT_DIR/scripts/build-release.sh" "INSTALL_APP_LAUNCHER_COMMAND"
need_text "$ROOT_DIR/scripts/build-release.sh" "INSTALL_APP_LAUNCHER_KEY"
need_text "$ROOT_DIR/scripts/build-release.sh" "INSTALL_BOOTANIMATION_ENABLE"
need_text "$ROOT_DIR/scripts/build-release.sh" "INSTALL_BOOTANIMATION_ZIP"
need_text "$ROOT_DIR/scripts/build-release.sh" "BOOT_KERNEL_SOURCE"
need_text "$ROOT_DIR/scripts/build-release.sh" "ENABLE_CAMERA_USERSPACE"
need_text "$ROOTFS_BUILDER" "20-installer-app-launcher.conf"
need_text "$ROOTFS_BUILDER" "INSTALL_APP_LAUNCHER_KEY"
need_text "$ROOTFS_BUILDER" "bind = SUPER, %s, exec, %s"
need_text "$ROOTFS_BUILDER" "INSTALL_BOOTANIMATION_ENABLE"
need_text "$ROOTFS_BUILDER" "configure_bootanimation"
need_text "$ROOTFS_BUILDER" "Disabling boot animation so verbose boot remains visible."
need_text "$ROOTFS_BUILDER" "Installing custom boot animation."
need_text "$README" "## Swapping The Root Distro"
need_text "$README" "The supported installer builds Arch Linux ARM"
need_text "$README" "not a package-list change"
need_text "$README" "matched pair"
need_text "$README" "INSTALL_KERNEL_TRACK=stable"
need_text "$README" "INSTALL_KERNEL_TRACK=camera"
need_text "$README" "explicit opt-in experimental IMX519 camera kernel track"
need_text "$PACKAGE_PREBUILT" "flash-prebuilt-oneplus6t.sh"
need_text "$FETCH_RELEASE_INPUTS" "RELEASE_INPUTS_READY"
need_text "$FETCH_RELEASE_INPUTS" "oneplus6t-release-inputs.tar.zst"
need_text "$FETCH_RELEASE_INPUTS" "vendor/pmos-oneplus-fajita/boot"
need_text "$FETCH_RELEASE_INPUTS" "vendor/pmos-compat-payload"
need_text "$FETCH_RELEASE_INPUTS" "vendor/pmos-reference"
need_text "$FETCH_RELEASE_INPUTS" "hexagonrpcd-*-aarch64.pkg.tar.*"
need_text "$FETCH_RELEASE_INPUTS" "firmware-oneplus-sdm845-sensors-*-any.pkg.tar.*"
need_text "$FETCH_RELEASE_INPUTS" "RELEASE_INPUTS_DOWNLOAD_ATTEMPTS"
need_text "$FETCH_RELEASE_INPUTS" "The installer will keep trying"
need_text "$FETCH_RELEASE_INPUTS" "Press Ctrl+C if you want to stop"
need_text "$FETCH_RELEASE_INPUTS" "HTTP 5[0-9][0-9]"
need_text "$FETCH_RELEASE_INPUTS" "The installer will give you another chance instead of quitting"
need_text "$FETCH_RELEASE_INPUTS" "gh auth login -h github.com -p https -s repo,read:org -w"
need_text "$MAKE_RELEASE_INPUTS" "Release input bundle built"
need_text "$MAKE_RELEASE_INPUTS" "INCLUDE_CAMERA_PACKAGES=\"\${INCLUDE_CAMERA_PACKAGES:-1}\""
need_text "$MAKE_RELEASE_INPUTS" "--exclude-camera"
need_text "$MAKE_RELEASE_INPUTS" "sha256sums.txt"
need_text "$MAKE_RELEASE_INPUTS" "vendor/pmos-compat-payload"
need_text "$MAKE_RELEASE_INPUTS" "vendor/pmos-reference"
need_text "$FOOT_CONF" "font=monospace:size=18.5"
need_text "$FOOT_CONF" "pad=8x8"
need_text "$HYPR_CONF" "workspace_swipe_touch = true"
need_text "$OVERLAY/usr/local/bin/start-hyprland" "plugin = \$hyperrotation_plugin"
need_text "$OVERLAY/usr/local/bin/start-hyprland" "09-oneplus6t-hyperrotation-runtime.conf"
need_text "$OVERLAY/usr/local/bin/start-hyprland" "/usr/bin/start-hyprland"
need_text "$OVERLAY/usr/local/bin/start-hyprland" "oneplus6t-desktop-launching"
need_text "$OVERLAY/usr/local/bin/start-hyprland" "exec \"\$launcher_exec\" --path \"\$hyprland_bin\""
need_text "$HYPR_CONF" "bind = SUPER, Return, exec, /usr/local/bin/oneplus6t-terminal"
reject_text "$HYPR_CONF" "tlauncher"
need_text "$HYPR_CONF" "No default app launcher is forced by this profile"
need_text "$HYPR_CONF" "bind = SUPER, K, exec, /usr/local/bin/oneplus6t-osk toggle"
need_text "$HYPR_CONF" "bind = SUPER, H, exec, sh -lc 'pkill -x wvkbd-deskintl || pkill -x wvkbd-mobintl || pkill -x wvkbd || true'"
need_text "$HYPR_CONF" "bind = SUPER, C, killactive"
need_text "$HYPR_CONF" "bind = SUPER, 1, workspace, 1"
need_text "$HYPR_CONF" "bind = SUPER, 0, workspace, 10"
need_text "$HYPR_CONF" "oneplus6t-desktop-ready"
need_text "$HYPR_CONF" "exec-once = sh -lc 'sleep 120; exec /usr/local/bin/oneplus6t-audio-profile'"
need_text "$HYPR_CONF" "exec-once = sh -lc 'sleep 120; command -v callaudiod >/dev/null 2>&1 && exec callaudiod; exit 0'"
need_text "$HYPR_CONF" "exec-once = sh -lc 'sleep 120; exec /usr/local/bin/oneplus6t-call-audio-watch'"
need_text "$HYPR_CONF" "exec-once = sh -lc 'sleep 90; exec gnome-calls --gapplication-service'"
need_text "$HYPR_CONF" "exec-once = sh -lc 'sleep 90; exec chatty --gapplication-service'"
need_text "$HYPR_CONF" "bindl = , XF86PowerOff, exec, hyprctl notify"
need_text "$HYPR_CONF" "Power key caught"
need_text "$HYPR_CONF" "bindel = , XF86AudioRaiseVolume, exec, /usr/local/bin/oneplus6t-volume up"
need_text "$HYPR_CONF" "bindel = , XF86AudioLowerVolume, exec, /usr/local/bin/oneplus6t-volume down"
need_text "$HYPR_CONF" "exec-once = /usr/local/bin/oneplus6t-auto-rotate"
need_text "$CONFIG_ENV" "ENABLE_HEXAGON_SENSORS=\"\${ENABLE_HEXAGON_SENSORS:-1}\""
need_text "$CONFIG_ENV" "INSECURE_ROOT_PASSWORD=\"\${INSECURE_ROOT_PASSWORD:-alarm}\""
need_text "$CONFIG_ENV" "INSECURE_ALARM_PASSWORD=\"\${INSECURE_ALARM_PASSWORD:-alarm}\""
need_text "$PROFILE_DIR/packages.txt" "opendoas"
need_file "$OVERLAY/etc/doas.conf"
need_text "$OVERLAY/etc/doas.conf" "permit nopass alarm cmd chvt"
need_text "$OVERLAY/etc/doas.conf" "permit persist :wheel"
need_text "$OVERLAY/etc/doas.conf" "permit setenv {PATH=/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin} :wheel"
need_text "$ROOTFS_BUILDER" "\$1 == \"wheel\""
need_text "$ROOTFS_BUILDER" "\$4 \",\" username"
need_text "$ROOTFS_BUILDER" "INSTALL_USERNAME=\"\${INSTALL_USERNAME:-alarm}\""
need_text "$ROOTFS_BUILDER" "configure_installer_identity"
need_text "$ROOTFS_BUILDER" "write_installer_wifi_config"
need_text "$ROOTFS_BUILDER" "write_installer_mobile_apn_config"
need_text "$ROOTFS_BUILDER" "\$MNT_DIR/home/\$INSTALL_USERNAME/.ssh"
need_text "$ROOTFS_BUILDER" "fix_privileged_helper_modes"
need_text "$ROOTFS_BUILDER" "usr/bin/su usr/bin/doas"
need_text "$ROOTFS_BUILDER" "chmod 4755 \"\$MNT_DIR/\$helper\""
need_text "$INSTALL_RELEASE" "ALLOW_INSECURE_DEFAULT_PASSWORD=\"\${ALLOW_INSECURE_DEFAULT_PASSWORD:-1}\""
need_text "$INSTALL_RELEASE" "INSTALLER_SETUP_PROMPT=\"\${INSTALLER_SETUP_PROMPT:-auto}\""
need_text "$INSTALL_RELEASE" "INSTALLER_PASSWORD_PROMPT=\"\${INSTALLER_PASSWORD_PROMPT:-auto}\""
need_text "$INSTALL_RELEASE" "Linux username"
need_text "$INSTALL_RELEASE" "Wi-Fi network name/SSID"
need_text "$INSTALL_RELEASE" "Configure mobile-data APN now?"
need_text "$INSTALL_RELEASE" "Boot intro video [Enter=bundled, none=verbose, or paste video path]"
need_text "$INSTALL_RELEASE" "scripts/replace-boot-video.sh"
need_text "$INSTALL_RELEASE" "boot intro: disabled, verbose boot visible"
need_text "$INSTALL_RELEASE" "prompt_for_password"
need_text "$INSTALL_RELEASE" "Press Enter without typing a password to use the temporary default."
need_text "$INSTALL_RELEASE" "temporary default passwords are enabled because no custom password was entered"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-mobile-data.service" "ONEPLUS6T_MOBILE_DATA_BOOT_DELAY=90"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-mobile-data" "AUTO_CONNECT requested but APN is unset; skipping boot-time mobile-data connect"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-wifi-remoteproc.service" "ONEPLUS6T_DESKTOP_READY_MARKER=/run/user/1000/oneplus6t-desktop-ready"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-wifi-remoteproc.service" "ONEPLUS6T_WIFI_FINAL_DELAY_SECONDS=60"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-load-wifi-remoteproc" "wait_for_desktop_ready"
need_text "$INSTALL_RELEASE" "answer^^"
need_text "$FULL_INSTALLER" "optional username, Wi-Fi, APN, and local password prompts"
need_text "$FULL_INSTALLER" "temporary root/user password defaults if password prompts are left blank"
need_text "$FULL_INSTALLER" "scripts/fetch-release-inputs.sh"
need_text "$FULL_INSTALLER" "interactive package review before rootfs build"
need_text "$FULL_INSTALLER" "bash -n scripts/review-profile-packages.sh"
need_text "$FULL_INSTALLER" "RELEASE_INPUTS_TAG"
need_text "$FULL_INSTALLER" "release input bundle fetched and verified before build"
need_text "$ROOT_DIR/scripts/flash-release.sh" "FASTBOOT_COMMAND_ATTEMPTS"
need_text "$ROOT_DIR/scripts/flash-release.sh" "Resume without rebuilding"
need_text "$ROOT_DIR/scripts/flash-release.sh" "using known OnePlus 6T vbmeta fallback size 0x10000"
need_text "$ROOT_DIR/scripts/flash-release.sh" "Retrying automatically. Press Ctrl+C now if you want to stop."
need_text "$INSTALL_RELEASE" "scripts/review-profile-packages.sh"
need_text "$INSTALL_RELEASE" "PACKAGE_MANIFEST=\"\$reviewed_package_manifest\""
need_text "$ROOTFS_BUILDER" "installer-selected local passwords for root and \$username"
need_text "$ROOTFS_BUILDER" "temporary default passwords are enabled because no custom password was entered"
need_text "$PACKAGE_REVIEW" "REVIEW_PROFILE_PACKAGES"
need_text "$PACKAGE_REVIEW" "normalize_profile_package_name"
need_text "$PACKAGE_ALIASES" "fastboot)"
need_text "$PACKAGE_ALIASES" "android-tools"
need_text "$ROOTFS_BUILDER" "normalize_profile_package_name"
need_text "$PACKAGE_REVIEW" "Press Enter to accept"
need_text "$PACKAGE_REVIEW" "+ pkg1 pkg2"
need_text "$PACKAGE_REVIEW" "- pkg1 pkg2"
need_text "$PROFILE_DIR/packages.txt" "foot"
need_text "$PROFILE_DIR/packages.txt" "fzf"
need_text "$PROFILE_DIR/packages.txt" "python-pillow"
need_text "$PROFILE_DIR/packages.txt" "gnome-calls"
need_text "$PROFILE_DIR/packages.txt" "chatty"
need_text "$PROFILE_DIR/packages.txt" "feedbackd"
need_text "$PROFILE_DIR/packages.txt" "callaudiod"
reject_text "$PROFILE_DIR/packages.txt" "ratty"
reject_text "$PROFILE_DIR/packages.txt" "kitty"
reject_text "$PROFILE_DIR/packages.txt" "glmark2"
reject_text "$PROFILE_DIR/packages.txt" "mesa-utils"
reject_text "$PROFILE_DIR/packages.txt" "linuxconsole"
reject_text "$PROFILE_DIR/packages.txt" "gtkmm-4.0"
reject_text "$PROFILE_DIR/packages.txt" "gtk4-layer-shell"
reject_text "$PROFILE_DIR/packages.txt" "libevdev"
reject_text "$PROFILE_DIR/packages.txt" "pam"
reject_text "$OVERLAY/usr/local/bin/oneplus6t-terminal" "exec kitty"
reject_text "$OVERLAY/usr/local/bin/oneplus6t-terminal" "exec ratty"
reject_text "$OVERLAY/usr/local/bin/oneplus6t-osk" "sysboard"
reject_text "$ROOTFS_BUILDER" "install_source_cache syslock"
reject_text "$ROOTFS_BUILDER" "oneplus6t-syslock-build.service"
need_text "$ROOTFS_BUILDER" "enable_system_unit hexagonrpcd-sdsp.service sysinit.target"
need_text "$ROOTFS_BUILDER" "enable_system_unit iio-sensor-proxy.service multi-user.target"
need_text "$ROOTFS_BUILDER" "oneplus6t-bootanimation.service"
need_text "$ROOTFS_BUILDER" "mask_system_unit \"\$unit\""
need_text "$OVERLAY/usr/local/bin/oneplus6t-uim-select" "ONEPLUS6T_UIM_QMI_TIMEOUT"
need_text "$OVERLAY/usr/local/bin/oneplus6t-uim-select" "try_target -d qrtr://0"
need_text "$OVERLAY/usr/local/bin/oneplus6t-uim-select" "--uim-get-card-status"
need_text "$OVERLAY/usr/local/bin/oneplus6t-uim-select" "Primary GW provisioning already selected on present SIM slot"
need_text "$OVERLAY/usr/local/bin/oneplus6t-uim-select" "wanted=\"\$slot\""
reject_text "$OVERLAY/usr/local/bin/oneplus6t-uim-select" "-pd qrtr://0"
reject_text "$OVERLAY/usr/local/bin/oneplus6t-uim-select" "--uim-noop"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-uim-select.service" "After=pmos-compat-rmtfs.service pmos-compat-pd-mapper.service oneplus6t-qcom-radio.service"
need_text "$AUDIO_PROFILE" "alsa_card.platform-sound HiFi"
need_text "$AUDIO_PROFILE" "Speaker"
need_text "$AUDIO_PROFILE" "/usr/local/bin/oneplus6t-audio-route loudspeaker"
need_text "$AUDIO_ROUTE" "Voice Call"
need_text "$AUDIO_ROUTE" "Earpiece"
need_text "$AUDIO_ROUTE" "speakerphone"
need_text "$AUDIO_ROUTE" "route_loudspeaker"
need_text "$AUDIO_ROUTE" "route_earpiece"
need_text "$AUDIO_ROUTE" "ONEPLUS6T_SESSION_USER"
need_text "$AUDIO_ROUTE" "alsaucm -c \"\$ucm_card\" set _verb HiFi set _enadev Speaker"
need_text "$AUDIO_ROUTE" "set _verb \"Voice Call\""
need_text "$AUDIO_ROUTE" "set _enadev Mic"
need_text "$AUDIO_ROUTE" "move-source-output"
need_text "$AUDIO_ROUTE" "set-default-source"
need_text "$AUDIO_ROUTE" "pro-output-0|output-0"
need_text "$AUDIO_ROUTE" "pro-output-2|output-2"
need_text "$AUDIO_ROUTE" "move-sink-input"
need_text "$OVERLAY/usr/local/bin/oneplus6t-call-audio-watch" "mmcli -m any --voice-list-calls"
need_text "$OVERLAY/usr/local/bin/oneplus6t-call-audio-watch" "mmcli -o \"\$path\""
need_text "$OVERLAY/usr/local/bin/oneplus6t-call-audio-watch" "\"\$route_cmd\" earpiece"
need_text "$OVERLAY/usr/local/bin/oneplus6t-call-audio-watch" "\"\$route_cmd\" loudspeaker"
need_text "$AUDIO_TEST" "Voice Call"
need_text "$AUDIO_TEST" "Earpiece"
need_text "$AUDIO_TEST" "pro-output-0|output-0"
need_text "$AUDIO_TEST" "pro-output-2|output-2"
need_text "$AUDIO_TEST" "ONEPLUS6T_AUDIO_TEST_AS_USER"
need_text "$AUDIO_TEST" "ONEPLUS6T_SESSION_USER"
need_text "$AUDIO_TEST" "restore_hifi"
need_file "$FAJITA_UCM/fajita.conf"
need_file "$FAJITA_UCM/HiFi.conf"
need_file "$FAJITA_UCM/VoiceCall.conf"
need_file "$SDM845_UCM/OnePlus 6T.conf"
need_file "$SDM845_UCM/oneplus-OnePlus6T-.conf"
need_file "$O6T_UCM/O6T.conf"
need_file "$SND_SOC_SDM845_UCM/O6T.conf"
need_text "$O6T_UCM/O6T.conf" "Define.CardId \"O6T\""
need_text "$SND_SOC_SDM845_UCM/O6T.conf" "Define.CardId \"O6T\""
need_text "$FAJITA_UCM/fajita.conf" "SectionUseCase.\"HiFi\""
need_text "$FAJITA_UCM/HiFi.conf" "SectionDevice.\"Speaker\""
need_text "$FAJITA_UCM/VoiceCall.conf" "SectionDevice.\"Earpiece\""
need_text "$FAJITA_UCM/VoiceCall.conf" "SectionDevice.\"Speaker\""
need_text "$FAJITA_UCM/VoiceCall.conf" "QUAT_MI2S_RX Voice Mixer VoiceMMode1"

need_file "$OVERLAY/etc/systemd/logind.conf.d/10-oneplus6t-power-key.conf"
need_text "$OVERLAY/etc/systemd/logind.conf.d/10-oneplus6t-power-key.conf" "HandlePowerKey=ignore"
need_text "$OVERLAY/etc/systemd/logind.conf.d/10-oneplus6t-power-key.conf" "HandlePowerKeyLongPress=ignore"

need_file "$OVERLAY/etc/systemd/system/oneplus6t-power-key-inhibit.service"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-power-key-inhibit.service" "systemd-inhibit --what=handle-power-key"

need_file "$OVERLAY/etc/systemd/system/oneplus6t-keychords.service"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-keychords.service" "/usr/local/sbin/oneplus6t-keychords"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-keychords" "ONEPLUS6T_ENABLE_LOCK"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-keychords" "lock screen disabled"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-keychords" "WAYLAND_DISPLAY=wayland-1"
need_file "$OVERLAY/etc/systemd/system/oneplus6t-touch-osk.service"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-touch-osk.service" "ConditionPathExists=/usr/local/sbin/oneplus6t-touch-osk"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-touch-osk.service" "/usr/local/sbin/oneplus6t-touch-osk"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-touch-osk.service" "ONEPLUS6T_TOUCH_OSK_RUN_BIN=/usr/local/bin/oneplus6t-osk"
reject_text "$OVERLAY/etc/systemd/system/oneplus6t-touch-osk.service" "After=systemd-udev-settle.service getty@tty1.service"
reject_text "$OVERLAY/etc/systemd/system/oneplus6t-touch-osk.service" "After=getty@tty1.service"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-touch-osk.service" "ONEPLUS6T_TOUCH_OSK_FINGERS=1"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-touch-osk.service" "ONEPLUS6T_TOUCH_OSK_TAP_FINGERS=1 2 3 4"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-touch-osk.service" "ONEPLUS6T_TOUCH_OSK_BOTTOM_SWIPE=1"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-touch-osk.service" "ONEPLUS6T_TOUCH_OSK_BOTTOM_SWIPE_START_MIN_Y=1650"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-touch-osk.service" "ONEPLUS6T_TOUCH_OSK_BOTTOM_SWIPE_MIN_DISTANCE=180"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "BTN_TOUCH"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "ABS_MT_TRACKING_ID"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "ABS_MT_POSITION_X"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "ABS_MT_POSITION_Y"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "exec python3 -"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "struct.Struct(\"llHHi\")"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "ONEPLUS6T_TOUCH_OSK_FINGERS"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "ONEPLUS6T_TOUCH_OSK_TAP_FINGERS"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "ONEPLUS6T_SESSION_USER"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "pwd.getpwuid"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "DBUS_SESSION_BUS_ADDRESS"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "runuser\", \"-u\", session_user"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "wvkbd gestures"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "bottom-edge swipe-up"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "remaining=\$((remaining - 1))"
reject_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "evtest \"\$device\" | while"
reject_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "stdbuf -o0 -e0 evtest"
reject_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "((count++))"
reject_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "((remaining--))"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-touch-osk" "oneplus6t-osk prefers wvkbd"
need_text "$OVERLAY/usr/local/bin/oneplus6t-screenshot" "grim -o"
need_text "$OVERLAY/usr/local/bin/oneplus6t-screenshot" "latest.png"
need_text "$OVERLAY/usr/local/bin/oneplus6t-lock" "DBUS_SESSION_BUS_ADDRESS=\"\$session_bus\""
need_text "$OVERLAY/usr/local/bin/oneplus6t-lock" "lock screen is not installed"
need_file "$OVERLAY/etc/systemd/system/oneplus6t-qcom-remoteproc.service"
need_executable "$OVERLAY/usr/local/sbin/oneplus6t-load-qcom-remoteproc"
need_executable "$OVERLAY/usr/local/sbin/oneplus6t-wait-fastrpc-sdsp"
need_executable "$OVERLAY/usr/local/sbin/oneplus6t-load-qcom-radio"
need_executable "$OVERLAY/usr/local/sbin/oneplus6t-load-wifi-remoteproc"
need_file "$OVERLAY/etc/modprobe.d/oneplus6t-delay-radio.conf"
need_file "$OVERLAY/etc/systemd/system/oneplus6t-qcom-radio.service"
need_file "$OVERLAY/etc/systemd/system/oneplus6t-wifi-remoteproc.service"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-qcom-remoteproc.service" "After=pmos-compat-tqftpserv.service"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-qcom-remoteproc.service" "Before=hexagonrpcd-sdsp.service"
need_text "$OVERLAY/usr/lib/systemd/system/hexagonrpcd-sdsp.service" "ExecStartPre=/usr/local/sbin/oneplus6t-wait-fastrpc-sdsp"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-qcom-radio.service" "ONEPLUS6T_ENABLE_WIFI_REMOTEPROC=0"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-wifi-remoteproc.service" "After=oneplus6t-qcom-radio.service NetworkManager.service ModemManager.service"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-wifi-remoteproc.service" "/usr/local/sbin/oneplus6t-load-wifi-remoteproc"

need_file "$OVERLAY/etc/systemd/system/getty@tty1.service.d/10-oneplus6t-autologin.conf"
need_text "$OVERLAY/etc/systemd/system/getty@tty1.service.d/10-oneplus6t-autologin.conf" "--autologin alarm"
need_text "$OVERLAY/etc/systemd/system/getty@tty1.service.d/10-oneplus6t-autologin.conf" "After=oneplus6t-pacman-keyring.service"
need_text "$OVERLAY/etc/systemd/system/getty@tty1.service.d/10-oneplus6t-autologin.conf" "After=oneplus6t-hyperrotation-build.service"
need_text "$OVERLAY/etc/systemd/system/getty@tty1.service.d/10-oneplus6t-autologin.conf" "oneplus6t-wvkbd-build.service"
reject_text "$OVERLAY/etc/systemd/system/getty@tty1.service.d/10-oneplus6t-autologin.conf" "oneplus6t-syslock-build.service"
need_file "$OVERLAY/etc/systemd/system/oneplus6t-bootanimation.service"
reject_text "$OVERLAY/home/alarm/.bash_profile" "/usr/local/bin/oneplus6t-boot-banner"
[[ ! -e "$OVERLAY/etc/systemd/system/oneplus6t-boot-banner.service" ]] || fail "tty ASCII boot banner service must not exist in crashdump-safe profile"

need_file "$OVERLAY/etc/systemd/system/oneplus6t-wvkbd-build.service"
need_file "$OVERLAY/etc/systemd/system/oneplus6t-pacman-keyring.service"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-pacman-keyring.service" "ConditionPathExists=!/var/lib/oneplus6t/pacman-keyring-ready"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-pacman-keyring.service" "ExecStart=/usr/local/sbin/oneplus6t-init-pacman-keyring"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-init-pacman-keyring" "seed_clock_from_image"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-init-pacman-keyring" "date -u -s"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-init-pacman-keyring" "reset_keyring"
need_file "$OVERLAY/etc/oneplus6t-cpu-power.conf"
need_file "$OVERLAY/etc/systemd/system/oneplus6t-cpu-power.service"
need_text "$OVERLAY/etc/oneplus6t-cpu-power.conf" "GOVERNOR_PREFERENCE="
need_text "$OVERLAY/etc/oneplus6t-cpu-power.conf" "MIN_FREQ_KHZ="
need_text "$OVERLAY/etc/oneplus6t-cpu-power.conf" "MAX_FREQ_KHZ="
need_text "$OVERLAY/etc/systemd/system/oneplus6t-cpu-power.service" "ExecStart=/usr/local/sbin/oneplus6t-cpu-power apply"
need_text "$ROOTFS_BUILDER" "oneplus6t-cpu-power.service"
need_text "$ROOTFS_BUILDER" "systemd-networkd-wait-online.service"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-gps" "--loc-get-engine-lock"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-haptics-test" "EVIOCSFF"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-gps" "--location-enable-gps-nmea"
need_text "$OVERLAY/etc/systemd/system/oneplus6t-wvkbd-build.service" "WVKBD_REF="
need_text "$OVERLAY/usr/local/sbin/oneplus6t-install-wvkbd" "wvkbd-\${layout}"
need_text "$OVERLAY/usr/local/sbin/oneplus6t-install-wvkbd" "make -C \"\$src\" \"LAYOUT=\$layout\" \"\$binary\""
reject_text "$OVERLAY/etc/systemd/system/oneplus6t-wvkbd-build.service" "oneplus6t-sysboard"

printf 'profile-ui-check: %s passed\n' "$PROFILE"
