#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PROFILE="${1:-oneplus-fajita}"
PROFILE_DIR="$ROOT_DIR/profiles/$PROFILE"
SOURCE_MANIFEST="${PACKAGE_MANIFEST:-$PROFILE_DIR/packages.txt}"
INSTALL_PROFILE_PACKAGES="${INSTALL_PROFILE_PACKAGES:-1}"
REVIEW_PROFILE_PACKAGES="${REVIEW_PROFILE_PACKAGES:-auto}"
SELECTED_MANIFEST="${PROFILE_PACKAGE_REVIEW_OUTPUT:-$ROOT_DIR/work/$PROFILE/package-review/packages.selected.txt}"

if [[ ! -f "$SOURCE_MANIFEST" ]]; then
  echo "Missing package manifest: $SOURCE_MANIFEST" >&2
  exit 1
fi

# shellcheck source=scripts/package-name-aliases.sh
source "$ROOT_DIR/scripts/package-name-aliases.sh"

load_packages() {
  mapfile -t packages < <(awk '
    /^[[:space:]]*($|#)/ { next }
    !seen[$1]++ { print $1 }
  ' "$SOURCE_MANIFEST")
  normalize_packages
}

normalize_packages() {
  local package normalized
  local next=()
  declare -A seen=()
  for package in "${packages[@]}"; do
    normalized="$(normalize_profile_package_name "$package")"
    if [[ "$package" != "$normalized" ]]; then
      echo "Package alias: $package -> $normalized ($(describe_profile_package_alias "$package"))" >&2
    fi
    if [[ -z "${seen[$normalized]:-}" ]]; then
      next+=("$normalized")
      seen[$normalized]=1
    fi
  done
  packages=("${next[@]}")
}

show_help() {
  cat >&2 <<'EOF'
Package review commands:
  Enter              accept the current package list
  + pkg1 pkg2        add package names
  - pkg1 pkg2        remove package names
  add pkg1 pkg2      add package names
  remove pkg1 pkg2   remove package names
  list               show the current list again
  reset              restore the profile default list
  abort              stop the installer before build/flash
EOF
}

show_packages() {
  local i=1
  printf '\nCurrent profile package list (%d packages):\n' "${#packages[@]}" >&2
  local package
  for package in "${packages[@]}"; do
    printf '  %3d  %s\n' "$i" "$package" >&2
    i=$((i + 1))
  done
}

valid_package_name() {
  [[ "$1" =~ ^[A-Za-z0-9@._+-]+$ ]]
}

has_package() {
  local wanted="$1"
  local package
  for package in "${packages[@]}"; do
    [[ "$package" == "$wanted" ]] && return 0
  done
  return 1
}

add_packages() {
  local package original
  if [[ "$#" -eq 0 ]]; then
    echo "No package names supplied after add/+." >&2
    return
  fi
  for package in "$@"; do
    if ! valid_package_name "$package"; then
      echo "Skipping invalid package name: $package" >&2
      continue
    fi
    original="$package"
    package="$(normalize_profile_package_name "$package")"
    if [[ "$original" != "$package" ]]; then
      echo "Package alias: $original -> $package ($(describe_profile_package_alias "$original"))" >&2
    fi
    if has_package "$package"; then
      echo "Already present: $package" >&2
      continue
    fi
    packages+=("$package")
    echo "Added: $package" >&2
  done
}

remove_packages() {
  local remove package keep
  local requested=("$@")
  local next=()

  if [[ "$#" -eq 0 ]]; then
    echo "No package names supplied after remove/-." >&2
    return
  fi

  for remove in "${requested[@]}"; do
    if ! valid_package_name "$remove"; then
      echo "Skipping invalid package name: $remove" >&2
    elif ! has_package "$remove"; then
      echo "Not present: $remove" >&2
    fi
  done

  for package in "${packages[@]}"; do
    keep=1
    for remove in "${requested[@]}"; do
      if [[ "$package" == "$remove" ]]; then
        keep=0
        echo "Removed: $package" >&2
        break
      fi
    done
    [[ "$keep" -eq 1 ]] && next+=("$package")
  done
  packages=("${next[@]}")
}

write_selected_manifest() {
  mkdir -p "$(dirname "$SELECTED_MANIFEST")"
  local tmp="$SELECTED_MANIFEST.tmp"
  {
    echo "# Generated by scripts/review-profile-packages.sh"
    echo "# Source: ${SOURCE_MANIFEST#"$ROOT_DIR/"}"
    echo "# This file is in work/ and is not committed."
    printf '%s\n' "${packages[@]}"
  } > "$tmp"
  mv "$tmp" "$SELECTED_MANIFEST"
}

should_review() {
  if [[ "$INSTALL_PROFILE_PACKAGES" != "1" ]]; then
    return 1
  fi

  case "$REVIEW_PROFILE_PACKAGES" in
    0|false|False|FALSE|no|No|NO|never)
      return 1
      ;;
    1|true|True|TRUE|yes|Yes|YES|always)
      if [[ -t 0 && -t 2 ]]; then
        return 0
      fi
      echo "REVIEW_PROFILE_PACKAGES=$REVIEW_PROFILE_PACKAGES requires an interactive terminal." >&2
      exit 1
      ;;
    auto|"")
      [[ -t 0 && -t 2 ]]
      ;;
    *)
      echo "Invalid REVIEW_PROFILE_PACKAGES=$REVIEW_PROFILE_PACKAGES" >&2
      echo "Use auto, 1, or 0." >&2
      exit 1
      ;;
  esac
}

load_packages

if ! should_review; then
  printf '%s\n' "$SOURCE_MANIFEST"
  exit 0
fi

cat >&2 <<EOF
Profile package review

The default package manifest is:
  ${SOURCE_MANIFEST#"$ROOT_DIR/"}

These packages will be installed into the generated Arch Linux ARM root image.
Press Enter to accept the current list, or type help for edit commands.
EOF

show_packages

while true; do
  printf '\nPackage changes [Enter=accept, help=list commands]: ' >&2
  IFS= read -r line
  case "$line" in
    "")
      write_selected_manifest
      printf '%s\n' "$SELECTED_MANIFEST"
      exit 0
      ;;
    help|\?)
      show_help
      ;;
    list|l)
      show_packages
      ;;
    reset|r)
      load_packages
      echo "Restored profile default package list." >&2
      show_packages
      ;;
    abort|quit|q)
      echo "Stopped before build." >&2
      exit 1
      ;;
    +*)
      # shellcheck disable=SC2086
      add_packages ${line#+}
      ;;
    -*)
      # shellcheck disable=SC2086
      remove_packages ${line#-}
      ;;
    add\ *)
      # shellcheck disable=SC2086
      add_packages ${line#add }
      ;;
    remove\ *|rm\ *)
      line="${line#remove }"
      line="${line#rm }"
      # shellcheck disable=SC2086
      remove_packages $line
      ;;
    *)
      echo "Unknown package review command: $line" >&2
      show_help
      ;;
  esac
done
